# Generated by Django 4.2.26 on 2025-11-09 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(help_text="Nota de 1 a 10")),
                (
                    "comment",
                    models.TextField(
                        help_text="Comentário sobre o jogo", max_length=500
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data de criação"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        default=None,
                        help_text="Jogo que está sendo avaliado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="Games.gamesmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuário que criou a avaliação",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game")},
            },
        ),
    ]
