# Generated by Django 4.2.26 on 2025-11-09 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GamesModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="Título do jogo", max_length=100)),
                (
                    "platforms",
                    models.CharField(
                        help_text="Plataformas suportadas", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descrição do jogo", max_length=500),
                ),
                ("release_date", models.DateField(help_text="Data de lançamento")),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
